### ISSUE TITLE
Cannot go to next level

### ISSUE THREAD

**Issue by cuixiping** [SarjuThakkar/Blockle#25]
Your game is interesting.
Have you given up on developing this game?

It cannot go to next level after player complete the first level.

**Comment by SarjuThakkar** [comment]
Hi cuixiping,

If you are familiar with Wordle, the concept is similar. Blockle is a social game. There is one level a day, and everyone gets the same level. The goal is to get the lowest score you can and share it with your friends to see who can do the best. It's supposed to be once a day to drive interaction as players will be waiting for the next level and build anticipation. You can definitely fork the project and make it have levels to progress from, but that was not my vision.

Thanks for your interest in the game! I am glad you enjoy it!

**Comment by cuixiping** [comment]
> 

Thank you for the explanation. I understand now.
