### ISSUE TITLE
No board loads

### ISSUE THREAD

**Issue by JMSDMP** [SarjuThakkar/Blockle#26]
Instead of loading the day's board, a gray box is on the screen. From looking at the console and the code, I think the game has run out of boards.

![console error](https://github.com/SarjuThakkar/Blockle/assets/85512771/f905a311-7b2e-4631-8e20-6f21de5ad1da)
![gray canvas](https://github.com/SarjuThakkar/Blockle/assets/85512771/d9a24f46-f87c-454b-aa3e-40dab82fe381)

**Comment by SarjuThakkar** [comment]
Thank you for pointing that out I have refreshed the boards

**Comment by SarjuThakkar** [comment]
Let me know if the issue persists

**Comment by SarjuThakkar** [comment]
You may also have to refresh or open in incognito for it to update
